name: GoTo CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Install dependencies
      working-directory: /home/runner/work/GoTo/GoTo/client
      run: npm install

    - name: Build project
      working-directory: /home/runner/work/GoTo/GoTo/client
      run: npm run build --if-present

    - name: Run tests
      working-directory: /home/runner/work/GoTo/GoTo/client
      run: npm test
